version: '3.8'
services:
  data-processor:
    build:
      args:
        PIPELINE_DL_DEF: "https://raw.githubusercontent.com/dx-junkyard/OpenData-Library/main/LocalGovDataProcessors/162116_city_imizu/PopulationData/pipeline_download.json"
      context: .
    volumes:
      - ./output:/output  # 出力ディレクトリをマウント

