version: '3.8'
services:
  data-processor:
    build:
      args:
        PIPELINE_DL_DEF: "https://raw.githubusercontent.com/dx-junkyard/OpenDataProcCodeLab/main/LocalGovData/162116_city_imizu/PopulationData/pipeline_download.json"
      context: .
    volumes:
      - .:/work  # 出力ディレクトリをマウント

