steps:
  - name: WebScraper
    type: web_scraper_step
    start_url: https://www.city.arao.lg.jp/
    user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.112 Safari/537.36
    output_dir: ./output
    progress_file: ./progress.json
    save_every: 10
    skip_flg: yes
  - name: WebDataToJson
    type: html2htaglayer_step
    progress_file: ./progress.json
    output_json_dir: ./output_json
    columns_yaml: ./pipeline/columns.yaml
    include_keywords: "相談,窓口,補助,支給,提出,利用,対象,料金,対象,登録,予約,申請,申込み,申し込み,施設,設備"
    skip_flg: yes
  - name: LLM(elyza) app Summary
    type: ollama_step
    progress_file: ./progress.json
    input_json_file: ./output_json/service_catalog.json
    output_json_file: ./output_json/service_catalog_llm_elyza.json
    llm_url: http://host.docker.internal:11434/v1/
    llm_model: lucas2024/llama-3-elyza-jp-8b:q5_k_m
    llm_api_key: ollama
    llm_prompt_file: ./pipeline/llm_prompt.txt
    skip_flg: yes
  - name: LLM(swallow) app Summary
    type: ollama_step
    progress_file: ./progress.json
    input_json_file: ./output_json/service_catalog.json
    output_json_file: ./output_json/service_catalog_llm_swallow.json
    llm_url: http://host.docker.internal:11434/v1/
    llm_model: schroneko/llama-3.1-swallow-8b-instruct-v0.1:latest
    llm_api_key: ollama
    llm_prompt_file: ./pipeline/llm_prompt.txt
    skip_flg: yes
  - name: Embedding step(elyza)
    type: embedding_step
    service_catalog_json: ./output_json/service_catalog_llm_elyza.json
    embeddings_file: ./output_json/service_catalog_embedding_elyza.json
    skip_flg: yes
  - name: Embedding step(swallow)
    type: embedding_step
    service_catalog_json: ./output_json/service_catalog_llm_swallow.json
    embeddings_file: ./output_json/service_catalog_embedding_swallow.json
    skip_flg: yes
