steps:
  - name: WebScraper
    type: web_scraper_step
    start_url: https://www.city.imizu.toyama.jp/
    user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.112 Safari/537.36
    output_dir: ./output
    progress_file: ./progress.json
    save_every: 50
    skip_flg: yes
  - name: ServiceCatalogCreattor
    type: service_catalog_creator_step
    progress_file: ./progress.json
    output_json_path: ./services.json
    skip_flg: yes
  - name: clustering
    type: experimental_step_a
    input_json_path: ./services.json
    output_json_path: ./services.kmean.json
    n_clusters: 5
    skip_flg: yes
